pipeline {
    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                dir('jenkins-calculator') {
                    bat 'python -m pip install -r requirements.txt'
                }
            }
        }

        stage('Test') {
            steps {
                dir('jenkins-calculator') {
                    bat 'python -m pytest -v'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('jenkins-calculator') {
                    bat 'docker build -t jenkins-calculator .'
                }
            }
        }

        stage('SAM Validate') {
            steps {
                dir('jenkins-calculator') {
                    bat 'sam validate'
                }
            }
        }

        stage('SAM Build') {
            steps {
                dir('jenkins-calculator') {
                    bat 'sam build'
                }
            }
        }
    }

    post {
        success {
            echo 'Jenkins pipeline completed successfully.'
        }

        failure {
            echo 'Jenkins pipeline failed. Check the console output.'
        }
    }
}